### ISSUE TITLE
Line 253 bracket out of line

### ISSUE THREAD

**Issue by AJSTEV** [DiabolusXMachina/Studio-1-Game#8]
On line 253, there is a bracket out of line and needs to be tabbed in.

**Comment by STEVTN1** [comment]
I'm not seeing any problems with line 253. Has somebody already fixed it?

**Comment by AJSTEV** [comment]
Seemingly so. I'll mark the problem as closed.

**Comment by huanh8** [comment]
Changing the position of brackets may course more potential issues
Be careful!
